Update Statsd tag serializer to allow falsy values
DataDog/dogstatsd-ruby pull request #290
Opened 2024-02-05 15:41 UTC by joseph-hughes

## Problem
If we provide a tag which has a boolean value, we are unable to properly track the `false` case, since the "true" string appears with the tag name, but the "false" string does not show up. This is because of this logic, which checks for tag value presence:

https://github.com/DataDog/dogstatsd-ruby/blob/517b830c9b9103ff37c4b642bcfa5eff7c47353a/lib/datadog/statsd/serialization/tag_serializer.rb#L58-L66

`true` is evaluated to present, so we would add that tag name and value; however, `false` is evaluated to _not_ present, so we would only add that tag name (not the value).

## Solution
First convert the tag value to a string before checking for presence. This does result in other values being deemed "present" now which were not previously though, such as `[]` and `{}`. Is this a problem though?

2024-12-12 20:29 UTC, joseph-hughes commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +          tag.delete('|,')
Looks like my editor chose to remove some whitespace here!

2026-01-06 21:28 UTC, marcotc commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +                escape_tag_content("#{name}:#{value}")
This gem supports Ruby [as low as 2.1](https://github.com/DataDog/dogstatsd-ruby/blob/bf701af2792ba443da206b17c439dbc47c47f38d/dogstatsd-ruby.gemspec#L34), so we cannot use `&.`, sorry :/

I suggest keeping the if/else as it was, and just change the check to a `nil`-check explicitly:

```suggestion
              if !value.nil?
                escape_tag_content("#{name}:#{value}")
              else
                escape_tag_content(name)
```

2026-05-07 18:55 UTC, joseph-hughes commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +          tag.delete('|,')
I removed this diff, since it conflicted with a later change on the master branch

2026-05-07 18:56 UTC, joseph-hughes commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +                escape_tag_content("#{name}:#{value}")
I wish to also ignore `nil` when casted to a string to be extra safe, so I went with this suggestion but updated it to:
```rb
if !value.nil? && !value.to_s.nil?
```

2026-05-07 19:11 UTC, joseph-hughes commented
Hi, @marcotc, @chouetz, @StephenWakely, and @rayz 👋🏼

Pinging to see if there's any feedback or blockers for this PR. Happy to make changes if needed. Thanks!

2026-05-07 19:22 UTC, marcotc commented
Hey @joseph-hughes, so sorry for the delay. The issue totally makes sense!
I'll take a look at the PR as a whole today.

2026-05-08 08:44 UTC, ivoanjo commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +                escape_tag_content("#{name}:#{value}")
(Unrelated to this PR but -- should we raise the minimum version for this gem? dd-trace-rb has moved on for a long time, so it's weird to still keep this one at 2.1)

2026-05-13 22:40 UTC, marcotc commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +                escape_tag_content("#{name}:#{value}")
👋  @joseph-hughes, was there any particular reason you'd want to check for `to_s.nil?`?

The contract of `to_s` is to return a `String`, thus a `to_s` method returning `nil` would not be respecting the contract: https://www.rubydoc.info/stdlib/core/Object%3Ato_s
This means that even if `dogstatsd-ruby` protects itself against `to_s` returning `nil`, the `value` object here will likely trigger an error in a different part of the code execution, as other libraries can call `to_s` expecting a `String`.

2026-05-13 22:42 UTC, marcotc commented on spec/statsd/serialization/tag_serializer_spec.rb
> +          'results in blank': double('some tag', to_s: ''),
I think that `'results in blank': double('some tag', to_s: ''),` tests the same scenario as `blank: ''`:
```suggestion
          blank: '',
          :false_value => false,
```

2026-05-15 01:39 UTC, joseph-hughes commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +                escape_tag_content("#{name}:#{value}")
@marcotc You're right 🤦🏼 My bad! I think it'd be fine just check nil

2026-05-15 01:39 UTC, joseph-hughes commented on spec/statsd/serialization/tag_serializer_spec.rb
> +          'results in blank': double('some tag', to_s: ''),
Great point! I'll remove this

2026-05-15 01:43 UTC, joseph-hughes commented on spec/statsd/serialization/tag_serializer_spec.rb
> +          'results in blank': double('some tag', to_s: ''),
Updated [here](https://github.com/DataDog/dogstatsd-ruby/compare/6d60e398e20c876021a741a3cbf3a40d00b08114..be8266b190cd616b29994c810c27dd505e7825b9)

2026-05-15 01:44 UTC, joseph-hughes commented on lib/datadog/statsd/serialization/tag_serializer.rb
> +                escape_tag_content("#{name}:#{value}")
Updated [here](https://github.com/DataDog/dogstatsd-ruby/compare/6d60e398e20c876021a741a3cbf3a40d00b08114..be8266b190cd616b29994c810c27dd505e7825b9)

2026-05-15 01:44 UTC, joseph-hughes commented
@marcotc Thanks again for the review! I just made some updates, so it should be ready for review again

2026-05-20 19:07 UTC, antifun commented
It would be lovely if this could be merged before someone on my team gets the idea to fork the library or bandaid around it with a Rubocop rule requiring `.to_s` on tag values 😇 anything I can do to help get this over the line?

2026-05-20 19:37 UTC, joseph-hughes commented
> It would be lovely if this could be merged before someone on my team gets the idea to fork the library or bandaid around it with a Rubocop rule requiring `.to_s` on tag values 😇 anything I can do to help get this over the line?

@antifun I'm waiting on a re-review from @marcotc, but I wonder if we can just use the ref of this commit to get this change until this goes through 🤔

2026-05-21 16:41 UTC, joseph-hughes commented
I just rebased off the `master` branch. No change in the diff for this PR

2026-07-02 12:28 UTC, joseph-hughes commented
Hi, @marcotc, @chouetz, @StephenWakely, and @rayz 👋🏼

Pinging again to see if there's any feedback or blockers for this PR. Happy to make changes if needed. Thanks!

2026-07-07 13:53 UTC, StephenWakely requested changes

2026-07-07 13:53 UTC, StephenWakely commented on spec/statsd/serialization/tag_serializer_spec.rb
> +        expect(subject.format(message_tags_hash)).to eq 'empty_array:[],missing,empty_hash:{},blank:,false_value:false,results in blank:,results in nil'
This test doesn't pass because of the `results in nil` test. I believe the `to_s.nil?` check was removed, so we should no longer test for it here.

Can you remove this from the test and then I'll get right on it so we won't have any more delays..

2026-07-07 18:20 UTC, joseph-hughes commented on spec/statsd/serialization/tag_serializer_spec.rb
> +        expect(subject.format(message_tags_hash)).to eq 'empty_array:[],missing,empty_hash:{},blank:,false_value:false,results in blank:,results in nil'
@StephenWakely Thanks for the catch!

I just pushed up a fix. [Here's](https://github.com/DataDog/dogstatsd-ruby/compare/743e283847672cd0b92de9a857fe4a2a76c012a2..e60761b975a1debdb335f348317185065ec0fd0e) the diff.

My apologies for not running the spec myself sooner to validate it

2026-07-08 09:31 UTC, StephenWakely commented on spec/statsd/serialization/tag_serializer_spec.rb
> +      it 'ignores nil values and formats all other falsy values correctly' do
@joseph-hughes slightly pedantic perhaps, but I guess it makes sense. Could you make this change please.

2026-07-08 20:01 UTC, joseph-hughes commented on spec/statsd/serialization/tag_serializer_spec.rb
> +      it 'ignores nil values and formats all other falsy values correctly' do
@StephenWakely No worries! That's a fair catch.

I just updated the commit. [Here's the diff](https://github.com/DataDog/dogstatsd-ruby/compare/e60761b975a1debdb335f348317185065ec0fd0e..d92f4a01362fde7a567f2bdeb05700ddfe6e6792)

2026-07-09 09:18 UTC, StephenWakely approved these changes
Awesome thank you. Sorry it had to take over two years!

This does have the potential to break other peoples code, but it is more correct so I think it is good to do. We'll make sure to highlight it in the changelog.

2026-07-09 09:19 UTC, merged